apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: headless-worker
  template:
    metadata:
      labels:
        app: headless-worker
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: worker
        image: dhananjoy/headless-fleet:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: HEADLESS
          value: "true"
        - name: CHROME_PATH
          value: /usr/bin/comium-browser
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
      # nodeSelector:
      #   cloud.google.com/gke-nodepool: headless-worker
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - topologyKey: "kubernetes.io/hostname"
      #         labelSelector:
      #           matchLabels:
      #             app: headless-worker
---
apiVersion: v1
kind: Service
metadata:
  name: headless-worker
  labels:
    app: headless-worker
spec:
  type: LoadBalancer
  ports:
  - name: headless-worker
    port: 3001
    targetPort: 3001
  selector:
    app: headless-worker
