apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-fleet
spec:
  replicas: 5
  selector:
    matchLabels:
      app: headless-fleet
  template:
    metadata:
      labels:
        app: headless-fleet
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: worker
        image: dhananjoy/headless-fleet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: HEADLESS
          value: "true"
        - name: CHROME_PATH
          value: /usr/bin/chromium-browser
        - name: NODE_ENV
          value: production
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
        resources:
          requests:
            memory: 10G
            cpu: 1600m
      nodeSelector:
        cloud.google.com/gke-nodepool: headless-fleet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: headless-fleet
---
apiVersion: v1
kind: Service
metadata:
  name: headless-master
  labels:
    app: headless-master
spec:
  type: LoadBalancer
  loadBalancerIP: LOAD_BALANCER_IP
  ports:
  - name: headless-master
    port: 3001
    targetPort: 3001
  selector:
    app: headless-fleet
